---
- name: "Creates backend app directory"
  become: yes
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  become: yes
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Check env variables"
  become: yes
  shell: |
    echo "${NODE_ENV}"
    echo "${BACKEND_PORT}"
    echo "${TYPEORM_MIGRATIONS_DIR}"

- name: "Installing Node Dependencies"
  become: yes
  shell: |
    cd ~/backend-app
    npm i
    npm install class-validator
- name: "Executing Node app with PM2"
  become: yes
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  become: yes
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: yes
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu